title: "Captions GPT"
content:
  h1: "Captions GPT"
  subtitle: "Your personal social media assistant"
  app_links:
    app_store:
      text: "App Store"
      url: "https://apps.apple.com/us/app/captions-gpt/id6572327589"
    google_play:
      text: "Google Play"
      url: "#"
image:
  src: "CaptionsGPT.png"
  alt: "Captions GPT"
footer:
  company_name: "QloudAI"
  year: 2024
  privacy_link: "https://docs.google.com/document/d/1ntLlqEi-jLHFPoy5DceKUpEYXdDHHBwpFjyTgFmDkXI/edit?usp=sharing"
  terms_link: "/terms"
  support_email: "support@captionsgpt.site"
  support_email_display: "support@captionsgpt.site"
