title: "Captions GPT"
content:
  h1: "Captions GPT"
  subtitle: "Caption your moments perfectly!"
  app_links:
    app_store:
      text: "App Store"
      url: "https://apps.apple.com/us/app/captions-gpt/id6572327589"
    google_play:
      text: "Google Play"
      url: "https://play.google.com/store/apps/details?id=com.qloudai.captionsgpt"
image:
  src: "CaptionsGPT.mp4"
  alt: "Captions GPT"
footer:
  company_name: "QloudAI"
  year: 2024
  privacy_link: "/privacy"
  terms_link: "/terms"
  support_email: "support@captionsgpt.site"
  support_email_display: "support@captionsgpt.site"
