title: "Captions GPT"
content:
  h1: "Captions GPT"
  subtitle: "DOWNLOAD THE APP"
  app_links:
    app_store:
      text: "App Store"
      url: "#"
    google_play:
      text: "Google Play"
      url: "#"
image:
  src: "CaptionsGPT.png"
  alt: "Weather App Interface"
footer:
  company_name: "QloudAI"
  year: 2024
  privacy_link: "privacy"
  terms_link: "terms"
  support_email: "support@germanwithnik.com"
  support_email_display: "support@germanwithnik.com"